### ISSUE TITLE
清晰术无法直接使用

### ISSUE THREAD

**Issue by ElainaFanBoy** [ayachi2897/nonebot2_plugin#1]
求适配

**Comment by ayachi2897** [comment]
那个仓库经常自动关闭了，建议还是自己搭个仓库使用，我这个移植的挺烂的，现在nonebot2也有同效果的插件，建议使用那边的

**Comment by ayachi2897** [comment]
> 求适配

那个仓库经常自动关闭了，建议还是自己搭个仓库使用，我这个移植的挺烂的，现在nonebot2也有同效果的插件，建议使用那边的。

**Comment by ayachi2897** [comment]
> > 求适配
> 
> 那个仓库经常自动关闭了，建议还是自己搭个仓库使用，我这个移植的挺烂的，现在nonebot2也有同效果的插件，建议使用那边的。

仓库搭建可以看这里https://www.yuque.com/chenbaiyu/pfrgkd/wdey72?#36e8398c

**Comment by ayachi2897** [comment]
> > > 求适配
> > 
> > 
> > 那个仓库经常自动关闭了，建议还是自己搭个仓库使用，我这个移植的挺烂的，现在nonebot2也有同效果的插件，建议使用那边的。
> 
> 仓库搭建可以看这里https://www.yuque.com/chenbaiyu/pfrgkd/wdey72?#36e8398c

nb2插件https://github.com/Staskaer/nonebot_plugin_RealESRGAN
